### ISSUE TITLE
Feature Request: Add support for DocumentDB Instances

### ISSUE THREAD

**Issue by dbayardAWS** [aws-solutions/instance-scheduler-on-aws#222] opened 2020-12-16 18:47 UTC
Given the similarities with RDS's CLI, would it be possible to add support for scheduling DocumentDB instances, too?

**Comment by gockle** [comment] 2020-12-21 20:34
Hi @dbayardAWS Thank you for reaching out, we will add this to our feature request backlog and try to include it in a future release of the solution.

**Comment by ajhindle** [comment] 2021-02-24 04:04
Hi, I'd be grateful to see this feature implemented also. 
The request for this has been open since at least 2019 (see linked issue below, it should be open).
This feature is needed because Document DB is expensive to run!
https://github.com/awslabs/aws-instance-scheduler/issues/111

**Comment by rakshb** [comment] 2023-06-23 15:59
This feature request has been prioritized in our backlog for a future release.

**Comment by rakshb** [comment] 2023-06-23 18:32
Duplicate of #336

**Closed by rakshb** 2023-06-23 18:32 UTC
Labels: feature request
