### ISSUE TITLE
Support ignore schedule tag value

### ISSUE THREAD

**Issue by vic614** [aws-solutions/instance-scheduler-on-aws#478] opened 2023-08-28 14:17 UTC
Hello, 

We are trying to use instance scheduler together with AWS config. Config rule will enforce the scheduler tag to present on all EC2 instances. We are planning to use "ignore" or "disabled" as the default scheduler tag value. 

We hope to get a feature for instance scheduler that whenever it sees an instance tagged with the schedule tag to be a specific value like "ignore" or "disabled", it won't modify the instance's state. 

Or it could be a new "dry-run" key on the schedule that won't actually change the state of an instance. 

Regards,

Victor Yan, AWS ProServe

**Comment by CrypticCabub** [comment] 2023-08-28 17:57
Thanks for sending this in!

I am closing this as a duplicate of https://github.com/aws-solutions/instance-scheduler-on-aws/issues/322 for easier tracking

**Closed by CrypticCabub** 2023-08-28 17:57 UTC
