### ISSUE TITLE
How Instance Scheduler handles "InsufficientInstanceCapacity error"

### ISSUE THREAD

**Issue by natalia-1702** [aws-solutions/instance-scheduler-on-aws#321] opened 2022-08-04 00:25 UTC
hi team,
When I am trying to "start"  ( by my customised Lambda function - not instance scheduler) whole bunch of EC2 instance at some specific busy time -  I am getting  **InsufficientInstanceCapacity** error.

**According to documentation:**
"InsufficientInstanceCapacity Error message: "An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4). We currently do not have sufficient capacity in the Availability Zone you requested." This error occurs if there isn't enough On-Demand capacity to complete your request."
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-launch-issue/

**How "instance scheduler by AWS" can handle InsufficientInstanceCapacity? Is there some notification to users about getting InsufficientInstanceCapacity? Additional retries? Lambda function execution will be interrupted and ALL instances will not be started? Or some of them will be started?  Could you please describe in more details.** 

Thank you.

**Comment by rakshb** [comment] 2023-06-27 17:56
Thanks for submitting this request. This has been added to the backlog and will be reviewed in a future release.

**Comment by CrypticCabub** [comment] 2023-07-03 12:54
hi @bradthurber does this error occur on a specific day of the week?

Also, do you have any schedules setup that would start specific instances only on that day? There is a known bug in the batching logic for Instance Scheduler that can cause an `InsufficientInstanceCapacity` error to prevent the entire batch to fail to start even if only 1 instance is impacted in the batch. The default batch size is 5, so up to 4 otherwise healthy instances can theoretically be impacted by each bad instance. Which means that it's quite possible that a particular set of bad instances (possibly of a single type?) are causing the error that you describe.

A fix for this batching issue will be included in our next release

**Comment by bradthurber** [comment] 2023-07-03 15:18
Hi @CrypticCabub,

Thank you very much for your reply. I am not the one who directly maintains the instance schedule for our team, but this does look like a possible match. We have a single m6i instance and a bunch of m5 instances that all start M-F at 7:30 am. It does look like the m6i instance may be failing to start and that may be impacting the m5 instances. We will certainly give the next release a try when it is available (we are on 1.4 now). 

Thanks again,
Brad

**Comment by SchnitzelKopf** [comment] 2023-07-10 12:01
Hello,  
When is this planned to be fixed? I cannot see any changes regarding this topic in 1.5.0.

We have 1000 Instances in our AWS Account.  They have different schedules. But the most common schedule is starting in the morning and starting for maintenance. This is an example where many instances were not started for our weekly maintenance.

`2023-07-03 01:05:36.119000+0200 (CEST) - ERROR   : Error starting instances i-06e7043fa9635cxxx,i-015f432659d513xxx,i-0a1463fabf390bxxx,i-0a323c3edc696cxxx,i-08299f9ed45a01xxx, (An error occurred (InsufficientInstanceCapacity) when calling the StartInstances operation (reached max retries: 4): Insufficient capacity.)`

Are there any options in AWS Scheduler to fix this behavior? F.e. increase retries to f.e. 10. 

Reading the previous comment from @bradthurber it seems like just one of these instances had insufficient capacity, but all of them weren't started? This is terrible for us as we probably have 100+ Instances using the same schedule.

Best Regards,  
Jean

**Comment by CrypticCabub** [comment] 2023-07-11 20:30
Hi @SchnitzelKopf

Under the current version of Instance Scheduler (1.5.0), no amount of extra retries will allow the extra instances to start because it is retrying with the same batch of instances (this being the cause of the bug). However if you go to the environment variables on the scheduler lambda (`{stack-name}-InstanceSchedulerMain`), you can set `START_EC2_BATCH_SIZE` to `1` to get around the issue at the cost of not having any batching on EC2 start calls.

We are actively working on this batching and retry logic (along with many other improvements) and hope to have it released in early August. Once released, batching will be handled dynamically and individual failing instances should no longer prevent otherwise healthy instances from starting/stopping

**Comment by hearde** [comment] 2023-07-24 19:30
Instance start failures cascading to all other instances in the batch has been fixed in [v1.5.1](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v1.5.1).

We do not currently have any plans to address insufficient capacity errors specifically.

**Closed** 2023-09-26 19:30 UTC
Labels: feature request
