### ISSUE TITLE
Enable stopping and starting of multi-AZ RDS instances

### ISSUE THREAD

**Issue by iainelder** [aws-solutions/instance-scheduler-on-aws#179] opened 2020-07-02 15:26 UTC
In november 2018 [Amazon RDS enabled stopping and starting of multi-AZ database instances](https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-rds-stop-and-start-of-multi-az-instances). The announcement explains why you might want to do this:

> Amazon RDS for MySQL, MariaDB, PostgreSQL, and Oracle now allow you to stop and start database instances that are running in a Multi-AZ configuration. This makes it easy and affordable to use databases for development and test purposes that match the configuration of your production databases but are not required to be running all of the time.

It's exactly the situation I encountered today in one client. We have a pre-production environment with an Oracle and a MySQL database in multi-AZ configurations. The databases are to be turned off outside office hours to save money.

The instance scheduler does not yet support this feature. Instead it logs a debug message and ignores the schedule.

```
2020-07-02 - 12:40:49.546 - DEBUG   : Can not schedule Multi-AZ or Mirrored database rds instance "exampledb"
```

Of course it once made sense that the instance scheduler behave like this because the limitation was imposed by the RDS service.

But now that RDS supports turning off multi-AZ, can we now do it in the instance scheduler too?

Thanks!

**Comment by iainelder** [comment] 2020-07-02 15:33
Turning off multi-AZ was first discussed in #136. The limitation of the RDS service ("multi az RDS instances cannot be stopped") no longer exists. So with this feature request that issue could also be resolved.

**Comment by gockle** [comment] 2020-07-15 20:13
Hi @iainelder, Thanks for providing the information, Can you provide us the details of which RDS engine (Ex: SQL Server, Aurora, PostgreSQL) you plan to schedule using the solution? 

Although this feature has been enabled its currently unavailable for SQL Server Instances as documented in the Limitations section of [Stop RDS Instances](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_StopInstance.html).

**Comment by iainelder** [comment] 2020-07-22 07:57
> Can you provide us the details of which RDS engine (Ex: SQL Server, Aurora, PostgreSQL) you plan to schedule using the solution?

Yes, the RDS engines that we would schedule in this way are Oracle and MySQL.

**Comment by rakshb** [comment] 2023-06-23 15:55
Closing since this is a duplicate of #136

**Closed by rakshb** 2023-06-23 15:55 UTC
Labels: feature request
