### ISSUE TITLE
Support Autoscaling Groups (Amazon ASG)

### ISSUE THREAD

**Issue by jiba21** [aws-solutions/instance-scheduler-on-aws#317] opened 2022-06-15 06:59 UTC
Hi,

Does the instance scheduler have future plan to support the scheduling of ASGs?
We would centralize in the same system the scheduler of all systems, like RDS and EC2. 

Thanks

**Comment by devstek** [comment] 2022-07-26 13:00
+1

**Comment by rakshb** [comment] 2023-06-23 18:17
This is prioritized for a future release. Closing this since it is a duplicate of #15

**Closed by rakshb** 2023-06-23 18:17 UTC
Labels: feature request
