### ISSUE TITLE
The timezone of auto tagging seems to be wrong.

### ISSUE THREAD

**Issue by y-isono** [aws-solutions/instance-scheduler-on-aws#295] opened 2021-12-09 02:19 UTC
The timezone of auto tagging seems to be wrong.

I created a period and and schedule like:

```
$ scheduler-cli create-period --stack <stack name> --name <period name> --begintime 10:45 --endtime 11:00 --weekdays mon-fri
{
   "Period": {
      "Begintime": "10:45",
      "Endtime": "11:00",
      "Name": "<period name>",
      "Weekdays": [
         "mon-fri"
      ],
      "Type": "period"
   }
}
```

```
$ scheduler-cli create-schedule --name <schedule name> --periods <period name>,weekends --timezone Asia/Tokyo --stack <stack name>
{
   "Schedule": {
      "Timezone": "Asia/Tokyo",
      "Name": "<schedule name>",
      "Periods": [
         "<period name>",
         "weekends"
      ],
      "StopNewInstances": true,
      "UseMaintenanceWindow": false,
      "RetainRunning": false,
      "Enforced": false,
      "Hibernate": false,
      "UseMetrics": false,
      "Type": "schedule"
   }
}
```

And, although I set `ScheduleMessage=Started on {year}/{month}/{day} at {hour}:{minute} {timezone}` as document[1], the timezone of tag value added automatically was UTC as follows:

- Added Tag
ScheduleMessage	: Started on 2021/12/09 at 01:45 UTC

Is this timezone of tag value expected ?
I expected the value of tag automatically added is like "Started on 2021/12/09 at 10:45 JTC".

Parameters:
DefaultTimezone	: Asia/Tokyo
StartedTags	: ScheduleMessage=Started on {year}/{month}/{day} at {hour}:{minute} {timezone}

[1] Solution Components - Automated tagging - https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html#automated-tagging

**Comment by gockle** [comment] 2021-12-09 20:39
Hi @y-isono The timezone for tagging instance is configured to always UTC.

**Comment by rakshb** [comment] 2023-06-26 18:22
This request has been prioritized for the next release of the solution. Closing since this is a duplicate of #263

**Closed by rakshb** 2023-06-26 18:22 UTC
Labels: feature request
