### ISSUE TITLE
Can't start instance without correct KMS permissions

### ISSUE THREAD

**Issue by ricardocaronasousa** [aws-solutions/instance-scheduler-on-aws#504] opened 2023-12-26 10:28 UTC
**Describe the bug**
With specific instances that use custom KMS keys, it isn't possible to start them via schedules due to lack of KMS permissions for those keys.

**To Reproduce**
Try to schedule an instance whose volumes are encrypted with custom KMS keys.

**Expected behavior**
The scheduler should be able to run for them, so the CloudFormation stack should have the possibility to add custom permissions to the Scheduler Role.

**Please complete the following information about the solution:**

- [x] Version: [1.5.3]
- [x] Region: [eu-central-1]
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses? N/A
- [x] Were there any errors in the CloudWatch Logs? No errors whatsoever, the logs are all fine and the instance tags are updated as if the instance is started.
      [Troubleshooting](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html)

**Screenshots**
N/A

**Additional context**
Solution found in: https://repost.aws/questions/QUOtvWgsUGQPW7xWOHDSosLQ/aws-instance-scheduler-not-working

**Comment by hearde** [comment] 2024-01-02 18:42
Please review the guidance in the IG [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/troubleshooting.html#encrypted-ec2-instances-not-starting). We will need to solve this for spoke accounts as well. I am open to suggestions.

Duplicate of #332 .

**Closed by hearde** 2024-01-02 18:42 UTC
Labels: bug
